language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jr17/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true jr17/react-test npm run test

after_success:
  - docker build -t jr17/multi-client ./client
  - docker build -t jr17/multi-nginx ./nginx
  - docker build -t jr17/multi-server ./server
  - docker build -t jr17/multi-worker ./worker
  # Log in to take the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to DockerHub
  - docker push jr17/multi-client
  - docker push jr17/multi-nginx
  - docker push jr17/multi-server
  - docker push jr17/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "DockerReact-env-1"
#   bucket_name: "elasticbeanstalk-eu-central-1-882242622157"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"
